# Generated by Django 5.1.4 on 2025-01-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='presentation_files/')),
            ],
            options={
                'verbose_name': 'Presentation File',
                'verbose_name_plural': 'Presentation Files',
            },
        ),
    ]
